import Link from 'next/link'
import { ArrowRight, CalendarCheck, Check, Database, Headphones, Mic2, PhoneCall, ShieldCheck, Sparkles, Stethoscope } from 'lucide-react'

const receptionists=[
  {name:'Sofia',role:'Warm & reassuring',lang:'English · Spanish',image:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=700&q=88',color:'from-emerald-900/10'},
  {name:'Marcus',role:'Calm & confident',lang:'English',image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=88',color:'from-rose-900/10'},
  {name:'Amara',role:'Bright & attentive',lang:'English · French',image:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=700&q=88',color:'from-amber-900/10'},
  {name:'Daniel',role:'Measured & professional',lang:'English · Korean',image:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=700&q=88',color:'from-blue-900/10'},
  {name:'Elena',role:'Gentle & patient',lang:'English · Spanish',image:'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=700&q=88',color:'from-violet-900/10'},
  {name:'James',role:'Friendly & direct',lang:'English',image:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=700&q=88',color:'from-teal-900/10'},
]

const schema={"@context":"https://schema.org","@type":"SoftwareApplication",name:'Corinne AI Receptionist',applicationCategory:'BusinessApplication',operatingSystem:'Web',description:'AI virtual receptionist software for dental and medical practices.',offers:{"@type":"Offer",price:'0',priceCurrency:'USD'}}
export default function Home(){return <main className="mesh min-h-screen overflow-hidden"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><nav className="mx-auto flex max-w-7xl items-center px-6 py-5"><Link href="/" className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[14px] bg-[#143f49] text-white"><Stethoscope size={20}/></span><span className="display text-2xl">Corinne</span></Link><div className="ml-auto hidden items-center gap-8 text-xs font-semibold text-[#5d777d] md:flex"><a href="#voices">Receptionists</a><a href="#how">How it works</a><a href="#integrations">Integrations</a><a href="#safety">Safety</a></div><Link href="/admin" className="ml-6 rounded-xl bg-[#147a76] px-4 py-2.5 text-xs font-bold text-white">Open admin</Link></nav>
<section className="mx-auto grid max-w-7xl items-center gap-12 px-6 pb-16 pt-12 lg:grid-cols-[.9fr_1.1fr] lg:pt-16"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-[#b9cecf] bg-white/70 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#147a76]"><Sparkles size={13}/>Meet your new front desk</div><h1 className="display text-5xl leading-[.98] tracking-[-.03em] sm:text-6xl lg:text-[72px]">A voice every patient<br/><i className="font-normal text-[#147a76]">feels good calling.</i></h1><p className="mt-6 max-w-xl text-base leading-7 text-[#5f797f]">Choose the AI receptionist who fits your practice. Each one answers, schedules, follows up, and makes outbound calls in a natural, patient-first voice.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/admin" className="flex items-center gap-2 rounded-xl bg-[#143f49] px-5 py-3.5 text-sm font-bold text-white">Build your receptionist <ArrowRight size={16}/></Link><a href="#voices" className="flex items-center gap-2 rounded-xl border border-[#bdced0] bg-white/70 px-5 py-3.5 text-sm font-bold"><Headphones size={16}/>Meet the voices</a></div><div className="mt-7 flex flex-wrap gap-5 text-[10px] font-semibold text-[#698187]"><span className="flex gap-1.5"><Check size={13} className="text-[#147a76]"/>24/7 coverage</span><span className="flex gap-1.5"><Check size={13} className="text-[#147a76]"/>Multilingual voices</span><span className="flex gap-1.5"><Check size={13} className="text-[#147a76]"/>Human handoff</span></div></div>
<div id="voices" className="relative"><div className="absolute -inset-4 rotate-1 rounded-[32px] border border-[#b9cdcf]"/><div className="relative overflow-hidden rounded-[28px] bg-[#102f37] p-3 shadow-2xl shadow-[#143f49]/25"><div className="mb-3 flex items-center justify-between px-2 py-1 text-white"><div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-[#71c8c1]">AI voice collection</p><p className="display mt-1 text-xl">Who will answer your calls?</p></div><span className="rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[9px] text-[#b7c9cb]">6 voices</span></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{receptionists.map((r,i)=><article key={r.name} className="group relative h-[210px] overflow-hidden rounded-[16px] bg-[#244951] sm:h-[225px]"><img src={r.image} alt={`${r.name}, ${r.role} AI receptionist voice persona`} className="h-full w-full object-cover object-top grayscale-[12%] transition duration-500 group-hover:scale-[1.035] group-hover:grayscale-0"/><div className={`absolute inset-0 bg-gradient-to-t ${r.color} via-transparent to-black/5`}/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#0d2930] via-[#0d2930]/88 to-transparent px-3 pb-3 pt-10 text-white"><div className="flex items-end justify-between gap-2"><div><h2 className="display text-xl leading-none">{r.name}</h2><p className="mt-1.5 text-[9px] font-semibold text-[#d4e1e2]">{r.role}</p><p className="mt-1 text-[8px] text-[#90aaae]">{r.lang}</p></div><button aria-label={`Preview ${r.name}'s voice`} className="grid size-8 shrink-0 place-items-center rounded-full border border-white/15 bg-white/10 text-[#7bdbd3] backdrop-blur-md transition hover:bg-[#68c8c0] hover:text-[#102f37]"><Mic2 size={13}/></button></div></div>{i===0&&<span className="absolute left-2 top-2 rounded-full bg-[#d8f0ed] px-2 py-1 text-[8px] font-bold text-[#126a67]">Most popular</span>}</article>)}</div><p className="px-2 pb-1 pt-3 text-center text-[8px] tracking-wide text-[#829fa4]">AI-GENERATED VOICE PERSONAS · ALWAYS DISCLOSED TO CALLERS</p></div></div></section>
<section id="how" className="bg-[#143f49] py-20 text-white"><div className="mx-auto max-w-7xl px-6"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#6fd0c8]">One calm system</p><div className="mt-3 grid gap-8 lg:grid-cols-2"><h2 className="display text-4xl sm:text-5xl">From first ring to<br/>confirmed appointment.</h2><p className="max-w-lg text-sm leading-7 text-[#afc2c5]">Corinne speaks naturally, follows your practice rules, and keeps every conversation connected to your schedule and patient records.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3"><Feature icon={PhoneCall} title="Answers and calls" text="Handle inbound calls and run reminders, recalls, and post-op follow-ups."/><Feature icon={CalendarCheck} title="Books accurately" text="Schedule, reschedule, and cancel using real-time practice availability."/><Feature icon={Database} title="Keeps systems in sync" text="Connect your PMS, EHR, calendar, or database from one secure admin area."/></div></div></section>
<section id="integrations" className="mx-auto max-w-7xl px-6 py-20"><div className="panel grid gap-10 rounded-[28px] p-7 lg:grid-cols-2 lg:p-12"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#147a76]">Works with your stack</p><h2 className="display mt-3 text-4xl">Connected to the systems your team already knows.</h2><p className="mt-4 text-sm leading-7 text-[#667f85]">Use ready-made connectors or a secure database connection for the tools unique to your practice.</p></div><div className="grid grid-cols-2 gap-3">{['Dentrix','Open Dental','Eaglesoft','Epic','athenahealth','PostgreSQL'].map(x=><div key={x} className="rounded-xl border border-[#d1dfe0] bg-white/70 p-4 text-xs font-bold">{x}</div>)}</div></div></section>
<section id="safety" className="mx-auto max-w-4xl px-6 pb-24 text-center"><ShieldCheck className="mx-auto text-[#147a76]" size={32}/><h2 className="display mt-4 text-4xl">Designed around patient trust.</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-7 text-[#667f85]">Role-based access, encrypted connections, audit trails, consent controls, and clear AI disclosure are built into the workflow.</p></section></main>}
function Feature({icon:Icon,title,text}){return <article className="rounded-2xl border border-white/10 bg-white/5 p-6"><Icon className="text-[#6fd0c8]"/><h3 className="display mt-5 text-2xl">{title}</h3><p className="mt-3 text-xs leading-6 text-[#afc2c5]">{text}</p></article>}
